Register candidate
techswitch-learners/testswitch-api pull request #11
Opened 2020-04-23 12:40 UTC by JamBai2812

Endpoint create for registering new candidates from a form submission:

front end requires these keys for the form:
firstName
lastName
email

The API then generates a Guid for the user and writes the data to the candidates table in the database.
Guid is 36 character string, will need to be used by the 'generateURL' endpoint to create the unique link.

2020-04-23 13:12 UTC, MichaelWalker requested changes
We should probably think a little harder about validation (and how we test that)... but otherwise looks nice! :)

2020-04-23 13:12 UTC, MichaelWalker commented on TestSwitchApi/TestSwitchApi/Models/Request/CandidateRequest.cs
> +        }
You should just be able to delete this constructor, because its the same as the default one :)

2020-04-23 13:12 UTC, MichaelWalker commented on TestSwitchApi/TestSwitchApi/Models/Response/CandidateRegisteredResponse.cs
> +}
Is this used anywhere?

2020-04-23 13:12 UTC, MichaelWalker commented on TestSwitchApi/TestSwitchApi/Repositories/CandidatesRepo.cs
> +            return response.Entity;
so... some validation questions
- should we allow someone to sign up without a First Name / Last Name / Email?
- should we allow 2 people with the same Email?
- are their any restrictions on the length of any of these fields?

2020-04-23 14:28 UTC, JamBai2812 commented on TestSwitchApi/TestSwitchApi/Models/Response/CandidateRegisteredResponse.cs
> +}
nope, forgot to delete

2020-04-23 14:28 UTC, JamBai2812 commented on TestSwitchApi/TestSwitchApi/Models/Request/CandidateRequest.cs
> +        }
deleted

2020-04-23 14:31 UTC, JamBai2812 commented on TestSwitchApi/TestSwitchApi/Repositories/CandidatesRepo.cs
> +            return response.Entity;
So yeah I thought about some similar validation that we did for the login page - ie. handle it with required={true}, is it better to validate on the server side too? And no probably should validate the email is unique, I'll have a look into that. Lengths are a problem in the DB so I'll carry those over to the validation in the end point!

2020-04-23 15:28 UTC, MichaelWalker commented on TestSwitchApi/TestSwitchApi/Repositories/CandidatesRepo.cs
> +            return response.Entity;
cool - client side validation is just to allow us to give really quick, clear feedback to the user (ie its all about good UX).

it doesn't do anything to actually prevent the user doing something we don't want them to do - ie they could still do stuff in Postman, or by editing the JS or any number of other ways.

if we actually want to stop someone doing something, it MUST be done server side.

in this case we've got 2 lines of defense.
- we can validate the model: https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1
- we can enforce constraints to the Database.

Validating the model gives nice clear error messages
Constraints on the DB are awesome at actually preventing stuff we don't want, but are likely to throw unclear error messages.

- for the email uniqueness - DB Unique constraint is nice and easy (can probably ignore nice error messages for now)
- making a field required I'd do both DB and Model Validation (`NOT NULL` for DB and `[Required]` on the model)
- length is already a restriction in the DB - adding matching validation to the model just helps us tell the user what they did wrong

2020-04-24 08:42 UTC, MichaelWalker commented on TestSwitchApi/TestSwitchApi/Models/Request/CandidateRequest.cs
> +        }
still seems to be here?

2020-04-24 08:42 UTC, MichaelWalker commented on TestSwitchApi/TestSwitchApi/Models/Response/CandidateRegisteredResponse.cs
> +}
still seems to be here?

2020-04-24 09:04 UTC, JamBai2812 commented on TestSwitchApi/TestSwitchApi/Models/Request/CandidateRequest.cs
> +        }
Oh I haven't pushed yet sorry

2020-04-24 09:05 UTC, JamBai2812 commented on TestSwitchApi/TestSwitchApi/Models/Response/CandidateRegisteredResponse.cs
> +}
pushed now

2020-04-24 09:39 UTC, JamBai2812 commented on TestSwitchApi/TestSwitchApi/Repositories/CandidatesRepo.cs
> +            return response.Entity;
Ok I think this is done now, only thing I would add is some unit tests, but I've done some manual testing in postman and seems to work! The DB already had all the correct restraints (NOT NULL for all columns and UNIQUE for email)

2020-04-24 09:41 UTC, MichaelWalker approved these changes

2020-04-24 09:41 UTC, MichaelWalker commented on TestSwitchApi/TestSwitchApi/Repositories/CandidatesRepo.cs
> +            return response.Entity;
nice! thanks

2020-04-24 09:51 UTC, merged